#!/usr/bin/env python3
"""
Extract ROTH's true 3D objects (furniture and similar props) as OBJ models.

Realms stores two kinds of object art. Most are flat sprites, but props that
need a real silhouette -- tables, chairs, chests -- carry actual geometry: a
vertex list plus a face list with per-face texture references. Those are the
entries whose image_type has the OBJECT_DATA bit set.

Ported from roth-editor's das.gd (parsing, ~570-600) and object_roth.gd
(triangulation, ~339-425).

Layout, all little-endian unless noted:
    header          22 bytes, ends with num_vertices
    vertices        16 bytes each; x,y,z int16 then 10 bytes padding
    face section    8-byte header; faces_array_size is BIG endian
    face            54 bytes, ends with edge_count
    edges           (edge_count + 1) uint16; vertex index is edge >> 4

Usage:
    python extract_meshes.py <PACK.DAS> -o out/meshes
"""

import argparse
import struct
from pathlib import Path

import extract_das as E

HEADER_FMT = "<BBHHHHIHIH"          # 22 bytes
HEADER_SIZE = struct.calcsize(HEADER_FMT)
VERTEX_SIZE = 16
FACE_SIZE = 54


def parse_mesh(d: bytes, entry: dict):
    """Parse one 3D object into vertices + triangulated faces."""
    off = entry["offset"]
    if off + HEADER_SIZE > len(d):
        return None
    (_mod, _it, _bx, _by, _u6, _u8, _uA,
     _bz, _u10, nverts) = struct.unpack_from(HEADER_FMT, d, off)
    if not (0 < nverts <= 4096):
        return None

    p = off + HEADER_SIZE
    verts = []
    for _ in range(nverts):
        if p + VERTEX_SIZE > len(d):
            return None
        # Components are (x, UP, y) -- the MIDDLE value is vertical, not the
        # third (ROTH_NATIVE_HANDOFF.md 5.5). One mesh unit is one world unit.
        #
        # Do NOT negate X. roth-editor does, but that is an artefact of Godot's
        # handedness rather than anything ROTH does (handoff 5.1).
        x, up, y = struct.unpack_from("<hhh", d, p)
        verts.append((x, up, y))
        p += VERTEX_SIZE

    if p + 8 > len(d):
        return None
    # sig(4) + unk(2) + faces_array_size(2, BIG endian)
    faces_size = struct.unpack_from(">H", d, p + 6)[0]
    p += 8

    faces, consumed = [], 4
    while consumed < faces_size:
        if p + FACE_SIZE > len(d):
            break
        tex_base = struct.unpack_from(">H", d, p + 0x0C)[0]   # big endian
        sub_tex = d[p + 0x1C]
        rflag1 = d[p + 0x16]
        edge_count = struct.unpack_from("<H", d, p + 0x34)[0]
        p += FACE_SIZE
        consumed += FACE_SIZE

        n = edge_count + 1
        if n > 64 or p + n * 2 > len(d):
            break
        edges = struct.unpack_from(f"<{n}H", d, p)
        p += n * 2
        consumed += n * 2

        idx = [e >> 4 for e in edges]
        if any(i >= len(verts) for i in idx):
            continue
        # Triangulation exactly as roth-editor does it: 5 edges describe a quad,
        # 4 describe a triangle. Other counts are not handled there either.
        if n == 5:
            tris = [(idx[0], idx[1], idx[2]), (idx[0], idx[2], idx[3])]
            uvs = [((0, 0), (0, 1), (1, 1)), ((0, 0), (1, 1), (1, 0))]
        elif n == 4:
            tris = [(idx[0], idx[1], idx[2])]
            uvs = [((0, 0), (0, 1), (1, 1))]
        else:
            continue
        faces.append({"tris": tris, "uvs": uvs, "tex": tex_base,
                      "sub": sub_tex, "flip_v": bool(rflag1 & 2)})

    if not faces:
        return None
    return {"verts": verts, "faces": faces}


def write_obj(mesh: dict, name: str, scale: float) -> tuple:
    """Emit an OBJ. Faces are grouped by texture so each becomes one surface."""
    lines = [f"# {name} - generated by roth_pipeline/extract_meshes.py", ""]
    for x, up, y in mesh["verts"]:
        # Vertices arrive as (x, up, y). GZDoom's model space is Doom's: X and Y
        # horizontal, Z up. So the vertical component goes last.
        lines.append(f"v {x * scale:.4f} {y * scale:.4f} {up * scale:.4f}")

    uv_list, uv_index = [], {}
    def uv_id(uv):
        if uv not in uv_index:
            uv_list.append(uv)
            uv_index[uv] = len(uv_list)
        return uv_index[uv]

    by_tex = {}
    for f in mesh["faces"]:
        by_tex.setdefault(f["tex"], []).append(f)

    body, order = [], []
    for tex, group in sorted(by_tex.items()):
        order.append(tex)
        body.append(f"usemtl ROTHSKIN{len(order)-1}")
        for f in group:
            for tri, tri_uv in zip(f["tris"], f["uvs"]):
                ids = []
                for vi, uv in zip(tri, tri_uv):
                    u, v = uv
                    if f["flip_v"]:
                        v = 1 - v
                    ids.append(f"{vi + 1}/{uv_id((u, v))}")
                body.append("f " + " ".join(ids))

    for u, v in uv_list:
        lines.append(f"vt {u} {v}")
    lines.append("")
    lines.extend(body)
    return "\n".join(lines) + "\n", order


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("das", type=Path)
    ap.add_argument("-o", "--out", type=Path, required=True)
    ap.add_argument("--scale", type=float, default=1.0)
    args = ap.parse_args()

    d = args.das.read_bytes()
    h = E.parse_header(d)
    fat = E.parse_fat(d, h)
    args.out.mkdir(parents=True, exist_ok=True)

    ok = fail = 0
    manifest = {}
    for e in fat:
        if E.classify(d, e) != "3d-object":
            continue
        mesh = parse_mesh(d, e)
        if not mesh:
            fail += 1
            continue
        obj, order = write_obj(mesh, f"OBJ{e['index']:04d}", args.scale)
        (args.out / f"OBJ{e['index']:04d}.obj").write_text(obj)
        manifest[e["index"]] = {"skins": order,
                                "verts": len(mesh["verts"]),
                                "faces": len(mesh["faces"])}
        ok += 1

    import json
    (args.out / "meshes.json").write_text(json.dumps(manifest, indent=1))
    print(f"{args.das.name}: {ok} meshes written, {fail} failed")
    for idx, info in sorted(manifest.items())[:8]:
        print(f"   OBJ{idx:04d}: {info['verts']:3} verts, {info['faces']:3} faces, "
              f"skins {info['skins'][:4]}")


if __name__ == "__main__":
    main()
